export enum GameEvent {
  // generated by the client
  RoomListRequested = 'room_list_requested',
  RoomJoinRequested = 'room_join_requested',
  GameStartRequested = 'game_start_requested',
  DieRollRequested = 'die_roll_requested',

  // happens on the server
  RoomListGenerated = 'room_list_generated',
  JoinedRoom = 'joined_room',
  RoomJoinFailed = 'room_join_failed',
  GameStarted = 'game_started',
  GameFinished = 'game_finished',
  DieRolled = 'die_rolled',
  DieRollFailed = 'die_roll_failed',
}
