version: "3.8"
services:
  db:
    image: postgres:15.2
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    ports:
      - ${DATABASE_PORT}:5432
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis:7.0.11
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - redis-data:/data
    command:
      - "redis-server"
      - "--requirepass"
      - "${REDIS_PASSWORD}"

volumes:
  db-data:
  redis-data:
