version: "3.8"
services:
  db:
    command:
      - "postgres"
      - "-c"
      - "log_statement=all"

  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
